deploy:      # This job runs in the deploy stage.
    stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
    when: manual
    script:
        - apk update && apk add curl
        - curl --request POST --form token=$TRIGGER_TOKEN --form ref=master --form variables[PROJECT]=bx-bot https://gitlab.binets.fr/api/v4/projects/560/trigger/pipeline