version: '3'


services:
    user_bot:
        build:
            context: ./
            dockerfile: user.Dockerfile
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - SAILORE_BX_BOT=${SAILORE_BX_BOT}
            - SAILORE_PARROT_BOT=${SAILORE_PARROT_BOT}
            - SAILORE_COMMITTEE_BOT=${SAILORE_COMMITTEE_BOT}
            - CALENDAR_ID=${CALENDAR_ID}
        ports:
            - "80:80"
        depends_on: 
            - redis
            - db
    
    parrot_bot:
        build:
            context: ./
            dockerfile: parrot.Dockerfile
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - SAILORE_BX_BOT=${SAILORE_BX_BOT}
            - SAILORE_PARROT_BOT=${SAILORE_PARROT_BOT}
            - SAILORE_COMMITTEE_BOT=${SAILORE_COMMITTEE_BOT}
            - CALENDAR_ID=${CALENDAR_ID}
        ports:
            - "8443:8443"
        depends_on: 
            - redis
            - db

    deadlines_bot:
        build:
            context: ./
            dockerfile: deadlines.Dockerfile
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - SAILORE_BX_BOT=${SAILORE_BX_BOT}
            - SAILORE_PARROT_BOT=${SAILORE_PARROT_BOT}
            - SAILORE_COMMITTEE_BOT=${SAILORE_COMMITTEE_BOT}
            - CALENDAR_ID=${CALENDAR_ID}

    redis:
        image: redis

    db:
        image: mariadb
        container_name: sailore-db
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_PASSWORD: 'password'
            MYSQL_USER: 'user'
        volumes:
            - mariadb-data:/var/lib/mysql

volumes:
    mariadb-data:
        